version: "3.8"

services:
  notebook:
    container_name: notebook
    build: .
    ports:
      - 8888:8888
      - 40000:40000
    environment:
      - DATASET_PATH=./questions_dataset/so_questions.csv
      - OUTPUT_PATH=./output
      - TOPICS_NUM=15
    volumes:
      - ./output/:/app/output
      - ./output/so_results:/app/output/so_results
      - ./extra_stop_words:/app/extra_stop_words

  notebook-test:
    container_name: notebook-test
    build:
      context: .
      dockerfile: DockerfileTest
    volumes:
      - "./notebook/:/home/notebook"
    command: bash -c "pytest -vv --cov"
